name: build

on: [push, pull_request]

permissions:
  contents: read

jobs:
  ui-tests:
    uses: ./.github/workflows/ui-tests.yml
    with:
      msys2-runtime-artifact-name: install
    permissions:
      contents: read
