name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup-msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true
          install: msys2-devel base-devel autotools cocom diffutils gcc gettext-devel libiconv-devel make mingw-w64-cross-crt mingw-w64-cross-gcc mingw-w64-cross-zlib perl zlib-devel xmlto docbook-xsl

      - name: Build
        shell: msys2 {0}
        run: |
          (cd winsup && ./autogen.sh)
          ./configure --disable-dependency-tracking --with-msys2-runtime-commit="$GITHUB_SHA"
          make -j8

      - name: Install
        shell: msys2 {0}
        run: |
          make DESTDIR="$(pwd)"/_dest install

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: install
          path: _dest/
